Anish_Nesarkar_Final_Project/Final4/Final4/Models/Job.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Final4.Models
{
    public class Job
    {
        [Key]
        public int JobId { get; set; }
        public string Role { get; set; }
        public string Company { get; set; }
        public string Location { get; set; }
        public string Details { get; set; }
        public string Duration { get; set; }
        public string Skills { get; set; }
        public string JobImage { get; set; }
    }
        
}

Anish_Nesarkar_Final_Project/Final4/Final4/Controllers/CommentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Final4.Models;
using Final4.Data;
using Microsoft.AspNetCore.Authorization;

namespace Final4.Controllers
{

    public class CommentsController : Controller
    {
        private readonly ApplicationDbContext context_;

        public CommentsController(ApplicationDbContext context)
        {
            context_ = context;

        }

        [HttpGet]
        public ActionResult CommentView()
        {
            if (User.IsInRole("Admin"))
            {
                return View(context_.comments.ToList<Comment>());
            }

            var commentList = context_.comments.Where(x => x.CommenterName == User.Identity.Name);
            return View(commentList);
        }



        [HttpGet]
        [Authorize(Roles = "Admin,User")] 
        public IActionResult AddComment(int id)
        {
            var model = new Comment();
            return View(model);
        }

        [HttpPost]
        [Authorize(Roles = "Admin,User")]
        public IActionResult AddComment(int id, Comment comment)
        {
            comment.CommenterName = User.Identity.Name;
            context_.comments.Add(comment);
            context_.SaveChanges();
            return RedirectToAction("CommentView");
        }



        //Delete Comment
        [Authorize(Roles = "Admin,User")]
        public IActionResult DeleteComment(int? id)
        {
            Comment comment = context_.comments.Find(id);
            context_.Entry(comment).State = Microsoft.EntityFrameworkCore.EntityState.Deleted;
            context_.SaveChanges();
            return RedirectToAction("CommentView");
        }




    }
}

Anish_Nesarkar_Final_Project/Final4/Final4/Controllers/ProfessionalController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Final4.Models;
using Final4.Data;
using Microsoft.AspNetCore.Authorization;

namespace Final4.Controllers
{
    //[Route("api/[controller]")]
    //[ApiController]
    public class ProfessionalController : Controller
    {
        private readonly ApplicationDbContext context_;

        public ProfessionalController(ApplicationDbContext context)
        {
            context_ = context;
            if (context_.internships.Count() == 0)
            {
                context_.internships.Add(new Internship { Role = "Embedded Software Developer", Company = "MIcrosoft Innovation Lab", Location = "PES University, Bangalore, India", Details = "Built Hand gesture controlled robotic arm", Duration = "3 months", Skills = "Embedded C, Sensor Interfacing, Control Algorithm" , InternImage = "/Images/mlab.png" } );
                context_.SaveChanges();
            }
        }

        [HttpGet]
        public IActionResult ProfessionalIndex()
        {
            return View();
        }

        //>---------------------< Internship methods >--------------------------

        public ActionResult InternView()
        {
            return View(context_.internships.ToList<Internship>());
        }


        [HttpGet]
        [Authorize(Roles = "Admin")]
        public IActionResult AddIntern(int id)
        {
            var model = new Internship();
            return View(model);
        }

        [HttpPost]
        public IActionResult AddIntern(int id, Internship intern)
        {
            intern.InternImage = "/Images/" + intern.InternImage;
            context_.internships.Add(intern);
            context_.SaveChanges();
            return RedirectToAction("InternView");
        }

        //Edit Internship

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public IActionResult EditIntern(int? id)
        {
            if (id == null)
            {
                return StatusCode(Microsoft.AspNetCore.Http.StatusCodes.Status400BadRequest);
            }
            Internship intern = context_.internships.Find(id);
            if (intern == null)
            {
                return StatusCode(StatusCodes.Status404NotFound);
            }
            return View(intern);
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public IActionResult EditIntern(int? id, Internship inter)
        {
            if (id == null)
            {
                return StatusCode(StatusCodes.Status400BadRequest);
            }
            var internship = context_.internships.Find(id);
            if (internship != null)
            {
                internship.Role = inter.Role;
                internship.Company = inter.Company;
                internship.Details = inter.Details;
                internship.Duration = inter.Duration;
                internship.Skills = inter.Skills;
                internship.Location = inter.Location;
                internship.InternImage = "/Images/" + inter.InternImage;
                try
                {
                    context_.SaveChanges();
                }
                catch (Exception)
                {
                    // do nothing for now
                }
            }
            return RedirectToAction("InternView");
        }


        //View Intern Details

        public ActionResult InternDetails(int? id)
        {
            if (id == null)
            {
                return StatusCode(StatusCodes.Status400BadRequest);
            }
            Internship intern = context_.internships.Find(id);

            if (intern == null)
            {
                return StatusCode(StatusCodes.Status404NotFound);
            }
            return View(intern);
        }

        //Delete Internship
        [Authorize(Roles = "Admin")]
        public IActionResult DeleteIntern(int? id)
        {
            Internship intern = context_.internships.Find(id);
            context_.Entry(intern).State = Microsoft.EntityFrameworkCore.EntityState.Deleted;
            context_.SaveChanges();
            return RedirectToAction("InternView");
        }


        //>------------------< Job Methods >--------------------<

        // [HttpGet("{id}")]
        [HttpGet]
        public ActionResult JobView()
        {      
            return View(context_.jobs.ToList<Job>());
        }


        [HttpGet]
        [Authorize(Roles = "Admin")]
        public IActionResult AddJob(int id)
        {
            var model = new Job();
            return View(model);
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public IActionResult AddJob(int id, Job job)
        {
            job.JobImage = "/Images/" + job.JobImage;
            context_.jobs.Add(job);
            context_.SaveChanges();
            return RedirectToAction("JobView");
        }

        //Edit Job

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public IActionResult EditJob(int? id)
        {
            if (id == null)
            {
                return StatusCode(Microsoft.AspNetCore.Http.StatusCodes.Status400BadRequest);
            }
            Job job = context_.jobs.Find(id);
            if (job == null)
            {
                return StatusCode(StatusCodes.Status404NotFound);
            }
            return View(job);
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public IActionResult EditJob(int? id, Job job)
        {
            if (id == null)
            {
                return StatusCode(StatusCodes.Status400BadRequest);
            }
            var job_ = context_.jobs.Find(id);
            if (job_ != null)
            {
                job_.Role = job.Role;
                job_.Company = job.Company;
                job_.Details = job.Details;
                job_.Duration = job.Duration;
                job_.Skills = job.Skills;
                job_.Location = job.Location;
                job_.JobImage = "/Images/" + job.JobImage;
                try
                {
                    context_.SaveChanges();
                }
                catch (Exception)
                {
                    // do nothing for now
                }
            }
            return RedirectToAction("JobView");
        }


        //View Job Details

        public ActionResult JobDetails(int? id)
        {
            if (id == null)
            {
                return StatusCode(StatusCodes.Status400BadRequest);
            }
            Job job = context_.jobs.Find(id);

            if (job == null)
            {
                return StatusCode(StatusCodes.Status404NotFound);
            }
            return View(job);
        }

        //Delete Job

        public IActionResult DeleteJob(int? id)
        {
            Job job = context_.jobs.Find(id);
            context_.Entry(job).State = Microsoft.EntityFrameworkCore.EntityState.Deleted;
            context_.SaveChanges();
            return RedirectToAction("JobView");
        }

    }
}

Anish_Nesarkar_Final_Project/Final4/Final4/Views/Professional/AddIntern.cshtml
@model Final4.Models.Internship
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@{
    ViewData["Title"] = "Add Internship";
}


<form asp-controller="Professional" asp-action="AddIntern" method="post">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="input-group">
        <label asp-for="Role" class="input-group-btn"></label>
        <input asp-for="Role" class="form-control" />
        <span asp-validation-for="Role" class="text-danger"></span>
    </div>
    <div class="input-group">
        <label asp-for="Company" class="input-group-btn"></label>
        <input asp-for="Company" class="form-control" />
        <span asp-validation-for="Company" class="text-danger"></span>
    </div>
    <div class="input-group">
        <label asp-for="Location" class="input-group-btn"></label>
        <input asp-for="Location" class="form-control" />
        <span asp-validation-for="Location" class="text-danger"></span>
    </div>
    <div class="input-group">
        <label asp-for="Details" class="input-group-btn"></label>
        <input asp-for="Details" class="form-control" />
        <span asp-validation-for="Details" class="text-danger"></span>
    </div>
    <div class="input-group">
        <label asp-for="Duration" class="input-group-btn"></label>
        <input asp-for="Duration" class="form-control" />
        <span asp-validation-for="Duration" class="text-danger"></span>
    </div>
    <div class="input-group">
        <label asp-for="Skills" class="input-group-btn"></label>
        <input asp-for="Skills" class="form-control" />
        <span asp-validation-for="Skills" class="text-danger"></span>
    </div>
    <div class="input-group">
        <label asp-for="InternImage" class="input-group-btn"></label>
        <input type="file" asp-for="InternImage" class="form-control" />
        <span asp-validation-for="InternImage" class="text-danger"></span>
    </div>
    <div class="form-group">
        <input type="submit" value="Create" class="btn btn-primary" />
    </div>
</form>

<div style="display:block;height:30px">
</div>

<footer style="bottom:0;width:100%;position:absolute;height:2.5rem;">
    <a href="https://www.linkedin.com/in/anishnesarkar/" target="_blank"><img style="margin-top:7px;" src="~/Images/linkedlnImage.png" height="40" width="40" /></a>
    <a href="https://www.facebook.com/anish.nkr" target="_blank"><img style="margin-top:7px;margin-left:7px" src="~/Images/facebook.png" height="40" width="40" /></a>
    <a href="https://www.instagram.com/anish_nkr/?hl=en" target="_blank"><img style="margin-top:7px;margin-left:7px" src="~/Images/anish_nkr_nametag.png" height="40" width="40" /></a>
    <a style="margin-left:75%" asp-controller="Professional" asp-action="InternView">Back</a>
</footer>

Anish_Nesarkar_Final_Project/Final4/Final4/Views/Professional/AddJob.cshtml
@model Final4.Models.Job
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@{
    ViewData["Title"] = "Add Job";
}


<form asp-controller="Professional" asp-action="AddJob" method="post">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="input-group">
        <label asp-for="Role" class="input-group-btn"></label>
        <input asp-for="Role" class="form-control" />
        <span asp-validation-for="Role" class="text-danger"></span>
    </div>
    <div class="input-group">
        <label asp-for="Company" class="input-group-btn"></label>
        <input asp-for="Company" class="form-control" />
        <span asp-validation-for="Company" class="text-danger"></span>
    </div>
    <div class="input-group">
        <label asp-for="Location" class="input-group-btn"></label>
        <input asp-for="Location" class="form-control" />
        <span asp-validation-for="Location" class="text-danger"></span>
    </div>
    <div class="input-group">
        <label asp-for="Details" class="input-group-btn"></label>
        <input asp-for="Details" class="form-control" />
        <span asp-validation-for="Details" class="text-danger"></span>
    </div>
    <div class="input-group">
        <label asp-for="Duration" class="input-group-btn"></label>
        <input asp-for="Duration" class="form-control" />
        <span asp-validation-for="Duration" class="text-danger"></span>
    </div>
    <div class="input-group">
        <label asp-for="Skills" class="input-group-btn"></label>
        <input asp-for="Skills" class="form-control" />
        <span asp-validation-for="Skills" class="text-danger"></span>
    </div>
    <div class="input-group">
        <label asp-for="JobImage" class="input-group-btn"></label>
        <input type="file" asp-for="JobImage" class="form-control" />
        <span asp-validation-for="JobImage" class="text-danger"></span>
    </div>
    <div class="form-group">
        <input type="submit" value="Create" class="btn btn-primary" />
    </div>
</form>

<div style="display:block;height:30px">
</div>
<footer style="bottom:0;width:100%;position:absolute;height:2.5rem;">
    <a href="https://www.linkedin.com/in/anishnesarkar/" target="_blank"><img style="margin-top:7px;" src="~/Images/linkedlnImage.png" height="40" width="40" /></a>
    <a href="https://www.facebook.com/anish.nkr" target="_blank"><img style="margin-top:7px;margin-left:7px" src="~/Images/facebook.png" height="40" width="40" /></a>
    <a href="https://www.instagram.com/anish_nkr/?hl=en" target="_blank"><img style="margin-top:7px;margin-left:7px" src="~/Images/anish_nkr_nametag.png" height="40" width="40" /></a>
    <a style="margin-left:75%" asp-controller="Professional" asp-action="JobView">Back</a>
</footer>

Anish_Nesarkar_Final_Project/Final4/Final4/Views/Professional/EditIntern.cshtml
@model Final4.Models.Internship
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@{
    ViewData["Title"] = "Edit Internship";
}


<form asp-controller="Professional" asp-action="EditIntern" method="post">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="InternshipId" />
    <div class="input-group">
        <label asp-for="Role" class="input-group-btn"></label>
        <input asp-for="Role" class="form-control" />
        <span asp-validation-for="Role" class="text-danger"></span>
    </div>
    <div class="input-group">
        <label asp-for="Company" class="input-group-btn"></label>
        <input asp-for="Company" class="form-control" />
        <span asp-validation-for="Company" class="text-danger"></span>
    </div>
    <div class="input-group">
        <label asp-for="Location" class="input-group-btn"></label>
        <input asp-for="Location" class="form-control" />
        <span asp-validation-for="Location" class="text-danger"></span>
    </div>
    <div class="input-group">
        <label asp-for="Details" class="input-group-btn"></label>
        <input asp-for="Details" class="form-control" />
        <span asp-validation-for="Details" class="text-danger"></span>
    </div>
    <div class="input-group">
        <label asp-for="Duration" class="input-group-btn"></label>
        <input asp-for="Duration" class="form-control" />
        <span asp-validation-for="Duration" class="text-danger"></span>
    </div>
    <div class="input-group">
        <label asp-for="Skills" class="input-group-btn"></label>
        <input asp-for="Skills" class="form-control" />
        <span asp-validation-for="Skills" class="text-danger"></span>
    </div>
    <div class="input-group">
        <label asp-for="InternImage" class="input-group-btn"></label>
        <input type="file" asp-for="InternImage" class="form-control" />
        <span asp-validation-for="InternImage" class="text-danger"></span>
    </div>
    <div class="form-group">
        <input type="submit" value="Save" class="btn btn-primary" />
    </div>
</form>

<div style="display:block;height:30px">
</div>

<footer style="bottom:0;width:100%;position:absolute;height:2.5rem;">
    <a href="https://www.linkedin.com/in/anishnesarkar/" target="_blank"><img style="margin-top:7px;" src="~/Images/linkedlnImage.png" height="40" width="40" /></a>
    <a href="https://www.facebook.com/anish.nkr" target="_blank"><img style="margin-top:7px;margin-left:7px" src="~/Images/facebook.png" height="40" width="40" /></a>
    <a href="https://www.instagram.com/anish_nkr/?hl=en" target="_blank"><img style="margin-top:7px;margin-left:7px" src="~/Images/anish_nkr_nametag.png" height="40" width="40" /></a>
    <a style="margin-left:75%" asp-controller="Professional" asp-action="InternView">Back</a>
</footer>

Anish_Nesarkar_Final_Project/Final4/Final4/Views/Professional/EditJob.cshtml
@model Final4.Models.Job
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@{
    ViewData["Title"] = "Edit Job";
}


<form asp-controller="Professional" asp-action="EditJob" method="post">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="JobId" />
    <div class="input-group">
        <label asp-for="Role" class="input-group-btn"></label>
        <input asp-for="Role" class="form-control" />
        <span asp-validation-for="Role" class="text-danger"></span>
    </div>
    <div class="input-group">
        <label asp-for="Company" class="input-group-btn"></label>
        <input asp-for="Company" class="form-control" />
        <span asp-validation-for="Company" class="text-danger"></span>
    </div>
    <div class="input-group">
        <label asp-for="Location" class="input-group-btn"></label>
        <input asp-for="Location" class="form-control" />
        <span asp-validation-for="Location" class="text-danger"></span>
    </div>
    <div class="input-group">
        <label asp-for="Details" class="input-group-btn"></label>
        <input asp-for="Details" class="form-control" />
        <span asp-validation-for="Details" class="text-danger"></span>
    </div>
    <div class="input-group">
        <label asp-for="Duration" class="input-group-btn"></label>
        <input asp-for="Duration" class="form-control" />
        <span asp-validation-for="Duration" class="text-danger"></span>
    </div>
    <div class="input-group">
        <label asp-for="Skills" class="input-group-btn"></label>
        <input asp-for="Skills" class="form-control" />
        <span asp-validation-for="Skills" class="text-danger"></span>
    </div>
    <div class="input-group">
        <label asp-for="JobImage" class="input-group-btn"></label>
        <input type="file" asp-for="JobImage" class="form-control" />
        <span asp-validation-for="JobImage" class="text-danger"></span>
    </div>
    <div class="form-group">
        <input type="submit" value="Save" class="btn btn-primary" />
    </div>
</form>

<div style="display:block;height:30px">
</div>
<footer style="bottom:0;width:100%;position:absolute;height:2.5rem;">
    <a href="https://www.linkedin.com/in/anishnesarkar/" target="_blank"><img style="margin-top:7px;" src="~/Images/linkedlnImage.png" height="40" width="40" /></a>
    <a href="https://www.facebook.com/anish.nkr" target="_blank"><img style="margin-top:7px;margin-left:7px" src="~/Images/facebook.png" height="40" width="40" /></a>
    <a href="https://www.instagram.com/anish_nkr/?hl=en" target="_blank"><img style="margin-top:7px;margin-left:7px" src="~/Images/anish_nkr_nametag.png" height="40" width="40" /></a>
    <a style="margin-left:75%" asp-controller="Professional" asp-action="JobView">Back</a>
</footer>

Anish_Nesarkar_Final_Project/Final4/Final4/Views/Professional/InternDetails.cshtml
@model Final4.Models.Internship

@{
    ViewData["Title"] = "Internship Details";
}


<div style="display:flex;margin-top:50px;justify-content:center">
    <img src="@Html.DisplayFor(model => model.InternImage)" width="300" height="300" />
</div>

<div style="display:flex;justify-content:center;margin-top:10px;font-size:20px;color:aquamarine">
    <b><u> @Html.DisplayFor(model => model.Role) </u></b>
</div>
<div style="display:flex;justify-content:center">
    @Html.DisplayFor(model => model.Company)
</div>
<div style="display:flex;justify-content:center">
    <span><b><u>Location : </u> : </b></span> @Html.DisplayFor(model => model.Location)
</div>
<div style="display:flex;justify-content:center">
    <span><b><u>Details </u> : </b></span> @Html.DisplayFor(model => model.Details)
</div>
<div style="display:flex;justify-content:center">
    <span><b><u>Duration </u> : </b></span> @Html.DisplayFor(model => model.Duration)
</div>
<div style="display:flex;justify-content:center">
    <span><b><u>Skills </u> : </b></span> @Html.DisplayFor(model => model.Skills)
</div>

<div style="display:block;height:30px">
</div>

<footer style="bottom:0;width:100%;position:absolute;height:2.5rem;">
    <a href="https://www.linkedin.com/in/anishnesarkar/" target="_blank"><img style="margin-top:7px;" src="~/Images/linkedlnImage.png" height="40" width="40" /></a>
    <a href="https://www.facebook.com/anish.nkr" target="_blank"><img style="margin-top:7px;margin-left:7px" src="~/Images/facebook.png" height="40" width="40" /></a>
    <a href="https://www.instagram.com/anish_nkr/?hl=en" target="_blank"><img style="margin-top:7px;margin-left:7px" src="~/Images/anish_nkr_nametag.png" height="40" width="40" /></a>
    <a style="margin-left:75%" asp-controller="Professional" asp-action="InternView">Back</a>
</footer>

Anish_Nesarkar_Final_Project/Final4/Final4/Views/Professional/InternView.cshtml
@model IEnumerable<Final4.Models.Internship>

@{
    ViewData["Title"] = "InternView";

}
@if (User.IsInRole("Admin"))
{
    <div style="display:flex;justify-content:flex-end">
        <a asp-action="AddIntern">Add New Internship</a>
    </div>
}
<div style="display:flex;width:1200px; justify-content:space-around">
    @foreach (var item in Model)
    {

        <div style="display:block;width:250px;height:100px;background-color:aquamarine;padding:70px 0;text-align:center">
            <a asp-action="InternDetails" asp-route-id="@item.InternshipId">
                @Html.DisplayFor(modelItem => item.Role)
            </a>
            @if (User.IsInRole("Admin"))
            {
                <p></p>
                <span><                  </span>
                <a asp-action="EditIntern" asp-route-id="@item.InternshipId">Edit</a> <span> | </span>
                <a asp-action="DeleteIntern" asp-route-id="@item.InternshipId">Delete</a> <span> > </span>

            }
        </div>


    }

</div>

<div style="display:block;height:30px">
</div>

<footer style="bottom:0;width:100%;position:absolute;height:2.5rem;">
    <h5 style="text-align:center"><b><a asp-controller="Comments" asp-action="CommentView">Add Comments/Notes</a></b></h5>
    <a href="https://www.linkedin.com/in/anishnesarkar/" target="_blank"><img style="margin-top:7px;" src="~/Images/linkedlnImage.png" height="40" width="40" /></a>
    <a href="https://www.facebook.com/anish.nkr" target="_blank"><img style="margin-top:7px;margin-left:7px" src="~/Images/facebook.png" height="40" width="40" /></a>
    <a href="https://www.instagram.com/anish_nkr/?hl=en" target="_blank"><img style="margin-top:7px;margin-left:7px" src="~/Images/anish_nkr_nametag.png" height="40" width="40" /></a>
    <a style="margin-left:75%" asp-controller="Professional" asp-action="ProfessionalIndex">Back</a>
</footer>

Anish_Nesarkar_Final_Project/Final4/Final4/Views/Professional/JobDetails.cshtml
@model Final4.Models.Job

@{
    ViewData["Title"] = "Job Details";
}


<div style="display:flex;margin-top:50px;justify-content:center">
    <img src="@Html.DisplayFor(model => model.JobImage)" width="300" height="300" />
</div>

<div style="display:flex;justify-content:center;margin-top:10px;font-size:20px;color:aquamarine">
    <b><u> @Html.DisplayFor(model => model.Role) </u></b>
</div>
<div style="display:flex;justify-content:center">
    @Html.DisplayFor(model => model.Company)
</div>
<div style="display:flex;justify-content:center">
    <span><b><u>Location : </u> : </b></span> @Html.DisplayFor(model => model.Location)
</div>
<div style="display:flex;justify-content:center">
    <span><b><u>Details </u> : </b></span> @Html.DisplayFor(model => model.Details)
</div>
<div style="display:flex;justify-content:center">
    <span><b><u>Duration </u> : </b></span> @Html.DisplayFor(model => model.Duration)
</div>
<div style="display:flex;justify-content:center">
    <span><b><u>Skills </u> : </b></span> @Html.DisplayFor(model => model.Skills)
</div>

<div style="display:block;height:30px">
</div>
<footer style="bottom:0;width:100%;position:absolute;height:2.5rem;">
    <a href="https://www.linkedin.com/in/anishnesarkar/" target="_blank"><img style="margin-top:7px;" src="~/Images/linkedlnImage.png" height="40" width="40" /></a>
    <a href="https://www.facebook.com/anish.nkr" target="_blank"><img style="margin-top:7px;margin-left:7px" src="~/Images/facebook.png" height="40" width="40" /></a>
    <a href="https://www.instagram.com/anish_nkr/?hl=en" target="_blank"><img style="margin-top:7px;margin-left:7px" src="~/Images/anish_nkr_nametag.png" height="40" width="40" /></a>
    <a style="margin-left:75%" asp-controller="Professional" asp-action="JobView">Back</a>
</footer>

Anish_Nesarkar_Final_Project/Final4/Final4/Views/Professional/JobView.cshtml
@model IEnumerable<Final4.Models.Job>
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@{
    ViewData["Title"] = "Job View";

}
@if (User.IsInRole("Admin"))
{
    <div style="display:flex;justify-content:flex-end">
        <a asp-action="AddJob">Add New Job</a>
    </div>
}
<div style="display:flex;width:1200px; justify-content:space-around">
    @foreach (var item in Model)
    {

        <div style="display:block;width:250px;height:100px;background-color:aquamarine;padding:70px 0;text-align:center">
            <a asp-action="JobDetails" asp-route-id="@item.JobId">
                @Html.DisplayFor(modelItem => item.Role)
            </a>
            @if (User.IsInRole("Admin"))
            {
                <p></p>
                <span><                  </span>
                <a asp-action="EditJob" asp-route-id="@item.JobId">Edit</a> <span> | </span>
                <a asp-action="DeleteJob" asp-route-id="@item.JobId">Delete</a> <span> > </span>

            }
        </div>

    }

</div>

<div style="display:block;height:30px">
</div>

<footer style="bottom:0;width:100%;position:absolute;height:2.5rem;">
    <h5 style="text-align:center"><b><a asp-controller="Comments" asp-action="CommentView">Add Comments/Notes</a></b></h5>
    <a href="https://www.linkedin.com/in/anishnesarkar/" target="_blank"><img style="margin-top:7px;" src="~/Images/linkedlnImage.png" height="40" width="40" /></a>
    <a href="https://www.facebook.com/anish.nkr" target="_blank"><img style="margin-top:7px;margin-left:7px" src="~/Images/facebook.png" height="40" width="40" /></a>
    <a href="https://www.instagram.com/anish_nkr/?hl=en" target="_blank"><img style="margin-top:7px;margin-left:7px" src="~/Images/anish_nkr_nametag.png" height="40" width="40" /></a>
    <a style="margin-left:75%" asp-controller="Professional" asp-action="ProfessionalIndex">Back</a>
</footer>

Anish_Nesarkar_Final_Project/Final4/Final4/Views/Professional/ProfessionalIndex.cshtml
@{
    ViewData["Title"] = "Professional";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div>
    <img src="~/Images/prof_background.png" height="400" width="1100" />
</div>

<div style="display:flex;width:1200px; justify-content:space-around">
    <div style="display:block;width:250px;height:100px;background-color:aquamarine;padding:70px 0;text-align:center"><a asp-action="JobView"><h3>Jobs</h3></a></div>
    <div style="display:block;width:250px;height:100px;background-color:aquamarine;padding:70px 0;text-align:center"><a asp-action="InternView"><h3>Internship</h3></a></div>
</div>

<div style="display:block;height:30px">
</div>

<footer style="bottom:0;width:100%;position:absolute;height:2.5rem;">
    <a href="https://www.linkedin.com/in/anishnesarkar/" target="_blank"><img style="margin-top:7px;" src="~/Images/linkedlnImage.png" height="40" width="40" /></a>
    <a href="https://www.facebook.com/anish.nkr" target="_blank"><img style="margin-top:7px;margin-left:7px" src="~/Images/facebook.png" height="40" width="40" /></a>
    <a href="https://www.instagram.com/anish_nkr/?hl=en" target="_blank"><img style="margin-top:7px;margin-left:7px" src="~/Images/anish_nkr_nametag.png" height="40" width="40" /></a>
    <a style="margin-left:75%" asp-controller="Home" asp-action="Index">Back</a>
</footer>