Anish_Nesarkar_Final_Project/Final4/Final4/Controllers/AcademicsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Final4.Models;
using Final4.Data;
using Microsoft.AspNetCore.Authorization;

namespace Final4.Controllers
{
    
    public class AcademicsController : Controller
    {
        private readonly ApplicationDbContext context_;

        public AcademicsController(ApplicationDbContext context)
        {
            context_ = context;
            if (context_.academicItems.Count() == 0)
            {
                context_.academicItems.Add(new AcademicItem { AcademicName = "Under-Graduate", College = "PES Institute of Technology", CourseWork = "Embedded Systems, Computer Networks, Data Structures, Internet Of Things", Major = "Electronics and Communication", yearOfCompletion = "2018" , gpa = 3.8F , AcadImage = "/Images/pesit.jpg"  }  );
                context_.academicItems.Add(new AcademicItem { AcademicName = "Graduate", College = "Syracuse University", CourseWork = "Design and Analysis of Algorithms, Software Modelling And Analysis, Internet Programming, Operating Systems, Object Oriented Programming", Major = "Computer Science", yearOfCompletion = "2020" , gpa = 3.4F , AcadImage = "/Images/SUImage.jpg" } );
                context_.SaveChanges();
            }
        }

        [HttpGet]
        public IActionResult AcademicIndex()
        {
            return View();
        }


        // [HttpGet("{id}")]
        public ActionResult AcadView(int id)
        {
            AcademicItem academicItem = context_.academicItems.Find(id);
            if (academicItem == null)
            {
                return StatusCode(StatusCodes.Status404NotFound);
            }
            List<AcademicItem> temp = new List<AcademicItem>();
            temp.Add(academicItem);
            return View(temp);
        }



        [HttpGet]
        [Authorize(Roles = "Admin")]
        public IActionResult AddAcad(int id)
        {
            var model = new AcademicItem();
            return View(model);
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public IActionResult AddAcad(int id, AcademicItem acad)
        {
            acad.AcadImage = "/Images/" + acad.AcadImage;
            context_.academicItems.Add(acad);
            context_.SaveChanges();
            return RedirectToAction("AcademicIndex");
        }

        //Edit Academic

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public IActionResult EditAcad(int? id)
        {
            if (id == null)
            {
                return StatusCode(Microsoft.AspNetCore.Http.StatusCodes.Status400BadRequest);
            }
            AcademicItem acad = context_.academicItems.Find(id);
            if (acad == null)
            {
                return StatusCode(StatusCodes.Status404NotFound);
            }
            return View(acad);
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public IActionResult EditAcad(int? id, AcademicItem acad)
        {
            if (id == null)
            {
                return StatusCode(StatusCodes.Status400BadRequest);
            }
            var academic = context_.academicItems.Find(id);
            if (academic != null)
            {
                academic.AcademicName = acad.AcademicName;
                academic.College = acad.College;
                academic.CourseWork = acad.CourseWork;
                academic.Major = acad.Major;
                academic.yearOfCompletion = acad.yearOfCompletion;
                academic.gpa = acad.gpa;
                academic.AcadImage = "/Images/" + acad.AcadImage;
                try
                {
                    context_.SaveChanges();
                }
                catch (Exception)
                {
                    // do nothing for now
                }
            }
            return RedirectToAction("AcademicIndex");
        }


        //View Academic Details

        public ActionResult AcadDetails(int? id)
        {
            if (id == null)
            {
                return StatusCode(StatusCodes.Status400BadRequest);
            }
            AcademicItem acad = context_.academicItems.Find(id);

            if (acad == null)
            {
                return StatusCode(StatusCodes.Status404NotFound);
            }
            return View(acad);
        }

        //Delete Academic
        [Authorize(Roles = "Admin")]
        public IActionResult DeleteAcad(int? id)
        {
            AcademicItem acad = context_.academicItems.Find(id);
            context_.Entry(acad).State = Microsoft.EntityFrameworkCore.EntityState.Deleted;
            context_.SaveChanges();
            return RedirectToAction("AcademicIndex");
        }




    }
}

Anish_Nesarkar_Final_Project/Final4/Final4/Controllers/CommentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Final4.Models;
using Final4.Data;
using Microsoft.AspNetCore.Authorization;

namespace Final4.Controllers
{

    public class CommentsController : Controller
    {
        private readonly ApplicationDbContext context_;

        public CommentsController(ApplicationDbContext context)
        {
            context_ = context;

        }

        [HttpGet]
        public ActionResult CommentView()
        {
            if (User.IsInRole("Admin"))
            {
                return View(context_.comments.ToList<Comment>());
            }

            var commentList = context_.comments.Where(x => x.CommenterName == User.Identity.Name);
            return View(commentList);
        }



        [HttpGet]
        [Authorize(Roles = "Admin,User")] 
        public IActionResult AddComment(int id)
        {
            var model = new Comment();
            return View(model);
        }

        [HttpPost]
        [Authorize(Roles = "Admin,User")]
        public IActionResult AddComment(int id, Comment comment)
        {
            comment.CommenterName = User.Identity.Name;
            context_.comments.Add(comment);
            context_.SaveChanges();
            return RedirectToAction("CommentView");
        }



        //Delete Comment
        [Authorize(Roles = "Admin,User")]
        public IActionResult DeleteComment(int? id)
        {
            Comment comment = context_.comments.Find(id);
            context_.Entry(comment).State = Microsoft.EntityFrameworkCore.EntityState.Deleted;
            context_.SaveChanges();
            return RedirectToAction("CommentView");
        }




    }
}

Anish_Nesarkar_Final_Project/Final4/Final4/Views/Academics/AcadDetails.cshtml
@model Final4.Models.AcademicItem

@{
    ViewData["Title"] = "Academic Details";
}


<div style="display:flex;margin-top:50px;justify-content:center">
    <img src="@Html.DisplayFor(model => model.AcadImage)" width="900" height="400" />
</div>

<div style="display:flex;justify-content:center;margin-top:10px;font-size:20px;color:aquamarine">
    <b><u> @Html.DisplayFor(model => model.AcademicName) </u></b>
</div>
<div style="display:flex;justify-content:center">
    @Html.DisplayFor(model => model.College)
</div>
<div style="display:flex;justify-content:center">
    <span><b><u>Major </u> : </b></span> @Html.DisplayFor(model => model.Major)
</div>
<div style="display:flex;justify-content:center">
    <span><b><u>CourseWork </u> : </b></span> @Html.DisplayFor(model => model.CourseWork)
</div>
<div style="display:flex;justify-content:center">
    <span><b><u>GPA </u> : </b></span> @Html.DisplayFor(model => model.gpa)
</div>

<div style="display:block;height:30px">
</div>

<footer style="bottom:0;width:100%;position:absolute;height:2.5rem;">
    
    <a href="https://www.linkedin.com/in/anishnesarkar/" target="_blank"><img style="margin-top:7px;" src="~/Images/linkedlnImage.png" height="40" width="40" /></a>
    <a href="https://www.facebook.com/anish.nkr" target="_blank"><img style="margin-top:7px;margin-left:7px" src="~/Images/facebook.png" height="40" width="40" /></a>
    <a href="https://www.instagram.com/anish_nkr/?hl=en" target="_blank"><img style="margin-top:7px;margin-left:7px" src="~/Images/anish_nkr_nametag.png" height="40" width="40" /></a>
    <a style="margin-left:75%" asp-controller="Academics" asp-action="AcademicIndex">Back</a>
</footer>

Anish_Nesarkar_Final_Project/Final4/Final4/Views/Academics/AcadView.cshtml
@model IEnumerable<Final4.Models.AcademicItem>

@{
    ViewData["Title"] = "AcadView";
}

@if (User.IsInRole("Admin"))
{
    <div style="display:flex;justify-content:flex-end">
        <a asp-action="AddAcad">Add New Academic Info</a>
    </div>
}
<div style="display:flex;width:1200px; justify-content:space-around">
    @foreach (var item in Model)
    {

        <div style="display:block;width:250px;height:100px;background-color:aquamarine;padding:70px 0;text-align:center">
            <a asp-action="AcadDetails" asp-route-id="@item.AcademicItemId">
                @Html.DisplayFor(modelItem => item.AcademicName)
            </a>
            @if (User.IsInRole("Admin"))
            {
                <p></p>
                <span><                  </span>
                <a asp-action="EditAcad" asp-route-id="@item.AcademicItemId">Edit</a> <span> | </span>
                <a asp-action="DeleteAcad" asp-route-id="@item.AcademicItemId">Delete</a> <span> > </span>

            }
        </div>

    }

</div>

<div style="display:block;height:30px">
</div>

<footer style="bottom:0;width:100%;position:absolute;height:2.5rem;">
    <a href="https://www.linkedin.com/in/anishnesarkar/" target="_blank"><img style="margin-top:7px;" src="~/Images/linkedlnImage.png" height="40" width="40" /></a>
    <a href="https://www.facebook.com/anish.nkr" target="_blank"><img style="margin-top:7px;margin-left:7px" src="~/Images/facebook.png" height="40" width="40" /></a>
    <a href="https://www.instagram.com/anish_nkr/?hl=en" target="_blank"><img style="margin-top:7px;margin-left:7px" src="~/Images/anish_nkr_nametag.png" height="40" width="40" /></a>
    <a style="margin-left:75%" asp-controller="Academics" asp-action="AcademicIndex">Back</a>
</footer>

Anish_Nesarkar_Final_Project/Final4/Final4/Views/Academics/AcademicIndex.cshtml
@{
    ViewData["Title"] = "Academics";
}

<div>
    <img src="~/Images/AcademicsImage.jpg" height="400" width="1100" />
</div>

<div style="display:flex;width:1200px;height:auto;justify-content:space-around">
    <div style="display:block;width:250px;height:100px;background-color:aquamarine;padding:70px 0;text-align:center"><a asp-action="AcadView" asp-route-id="1"><h3>Under-Graduate</h3></a></div>
    <div style="display:block;width:250px;height:100px;background-color:aquamarine;padding:70px 0;text-align:center"><a asp-action="AcadView" asp-route-id="2"><h3>Graduate</h3></a></div>
</div>

<div style="display:block;height:30px">
</div>
<footer style="bottom:0;width:100%;position:absolute;height:2.5rem;">
    <h5 style="text-align:center"><b><a asp-controller="Comments" asp-action="CommentView">Add Comments/Notes</a></b></h5>
    <a href="https://www.linkedin.com/in/anishnesarkar/" target="_blank"><img style="margin-top:7px;" src="~/Images/linkedlnImage.png" height="40" width="40" /></a>
    <a href="https://www.facebook.com/anish.nkr" target="_blank"><img style="margin-top:7px;margin-left:7px" src="~/Images/facebook.png" height="40" width="40" /></a>
    <a href="https://www.instagram.com/anish_nkr/?hl=en" target="_blank"><img style="margin-top:7px;margin-left:7px" src="~/Images/anish_nkr_nametag.png" height="40" width="40" /></a>
    <a style="margin-left:75%" asp-controller="Home" asp-action="Index">Back</a>
</footer>

Anish_Nesarkar_Final_Project/Final4/Final4/Views/Academics/AddAcad.cshtml
@model Final4.Models.AcademicItem
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@{
    ViewData["Title"] = "Add Academic Item";
}


<form asp-controller="Academics" asp-action="AddAcad" method="post">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="input-group">
        <label asp-for="AcademicName" class="input-group-btn"></label>
        <input asp-for="AcademicName" class="form-control" />
        <span asp-validation-for="AcademicName" class="text-danger"></span>
    </div>
    <div class="input-group">
        <label asp-for="College" class="input-group-btn"></label>
        <input asp-for="College" class="form-control" />
        <span asp-validation-for="College" class="text-danger"></span>
    </div>
    <div class="input-group">
        <label asp-for="Major" class="input-group-btn"></label>
        <input asp-for="Major" class="form-control" />
        <span asp-validation-for="Major" class="text-danger"></span>
    </div>
    <div class="input-group">
        <label asp-for="CourseWork" class="input-group-btn"></label>
        <input asp-for="CourseWork" class="form-control" />
        <span asp-validation-for="CourseWork" class="text-danger"></span>
    </div>
    <div class="input-group">
        <label asp-for="yearOfCompletion" class="input-group-btn"></label>
        <input asp-for="yearOfCompletion" class="form-control" />
        <span asp-validation-for="yearOfCompletion" class="text-danger"></span>
    </div>
    <div class="input-group">
        <label asp-for="gpa" class="input-group-btn"></label>
        <input asp-for="gpa" class="form-control" />
        <span asp-validation-for="gpa" class="text-danger"></span>
    </div>
    <div class="input-group">
        <label asp-for="AcadImage" class="input-group-btn"></label>
        <input type ="file" asp-for="AcadImage" class="form-control" />
        <span asp-validation-for="AcadImage" class="text-danger"></span>
    </div>
    <div class="form-group">
        <input type="submit" value="Create" class="btn btn-primary" />
    </div>
</form>

Anish_Nesarkar_Final_Project/Final4/Final4/Views/Academics/EditAcad.cshtml
@model Final4.Models.AcademicItem
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@{
    ViewData["Title"] = "Edit Academic Item";
}


<form asp-controller="Academics" asp-action="EditAcad" method="post">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="AcademicItemId" />
    <div class="input-group">
        <label asp-for="AcademicName" class="input-group-btn"></label>
        <input asp-for="AcademicName" class="form-control" />
        <span asp-validation-for="AcademicName" class="text-danger"></span>
    </div>
    <div class="input-group">
        <label asp-for="College" class="input-group-btn"></label>
        <input asp-for="College" class="form-control" />
        <span asp-validation-for="College" class="text-danger"></span>
    </div>
    <div class="input-group">
        <label asp-for="Major" class="input-group-btn"></label>
        <input asp-for="Major" class="form-control" />
        <span asp-validation-for="Major" class="text-danger"></span>
    </div>
    <div class="input-group">
        <label asp-for="CourseWork" class="input-group-btn"></label>
        <input asp-for="CourseWork" class="form-control" />
        <span asp-validation-for="CourseWork" class="text-danger"></span>
    </div>
    <div class="input-group">
        <label asp-for="yearOfCompletion" class="input-group-btn"></label>
        <input asp-for="yearOfCompletion" class="form-control" />
        <span asp-validation-for="yearOfCompletion" class="text-danger"></span>
    </div>
    <div class="input-group">
        <label asp-for="gpa" class="input-group-btn"></label>
        <input asp-for="gpa" class="form-control" />
        <span asp-validation-for="gpa" class="text-danger"></span>
    </div>
    <div class="input-group">
        <label asp-for="AcadImage" class="input-group-btn"></label>
        <input type="file" asp-for="AcadImage" class="form-control" />
        <span asp-validation-for="AcadImage" class="text-danger"></span>
    </div>
    <div class="form-group">
        <input type="submit" value="Save" class="btn btn-primary" />
    </div>
</form>