Anish_Nesarkar_Final_Project/Final4/Final4/Models/Project.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Final4.Models
{
    public class Project
    {
        [Key]
        public int ProjectId { get; set; }
        public string ProjectName { get; set; }
        public string Details { get; set; }
        public string Duration { get; set; }
        public string Skills { get; set; }
        public string link { get; set; }
        public string projectImage { get; set; }
    }

}

Anish_Nesarkar_Final_Project/Final4/Final4/Controllers/AchievementController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Final4.Models;
using Final4.Data;
using Microsoft.AspNetCore.Hosting;
using System.IO;
using Microsoft.AspNetCore.Authorization;

namespace Final4.Controllers
{
    public class AchievementController : Controller
    {
        private readonly ApplicationDbContext context_;
        private const string sessionId_ = "SessionId";
        
        public AchievementController(IHostingEnvironment hostingEnvironment,ApplicationDbContext context)
        {
            
            context_ = context;
            if (context_.projects.Count() == 0)
            {
               context_.projects.Add(new Project { ProjectName = "Small Scale IoT-enabled Automated greenhouse", Details  = "Built an automated greenhouse from scratch as a part of final year project", Duration = "5 months", Skills = "Embedded C, Sensor Interfacing, Control Algorithm", projectImage = "/Images/greenhouse.JPG", link = "https://drive.google.com/open?id=1j2jKbtsIIIhQlnWpo-AeTEPMBjoIzFu8" } );
                context_.honorsAndAwards.Add(new HonorsAndAwards { AwardName = "MHRD Merit Scholarship", AwardYear = "2017", AwardImage = "/Images/AwardsImage.png" });
                context_.researchPublications.Add(new ResearchPublication { researchName = "Design and Implementation of Hybrid methodology for IOT Data", Conference = "IEEE 2017 International Conference On Smart Technologies For Smart Nation (SmartTechCon)", researchYear = "2017", link = "https://ieeexplore.ieee.org/document/8358562", researchImage = "/Images/research_image.png" });
                context_.SaveChanges();
            }
        }

        public IActionResult CommentIndex()
        {
            return RedirectToAction("CommentView", "Comments");
        }

        [HttpGet]
        public IActionResult AchievementIndex()
        {
            return View();
        }


        //>--------------< Project Methods >--------------------<

        [HttpGet]
        public ActionResult ProjectView()
        {
            return View(context_.projects.ToList<Project>());
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public IActionResult AddProject(int id)
        {
            var model = new Project();
            return View(model);
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public IActionResult AddProject(int id, Project proj)
        {
            proj.projectImage = "/Images/" + proj.projectImage;
            context_.projects.Add(proj);
            context_.SaveChanges();
            return RedirectToAction("ProjectView");
        }

        //Edit Projects

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public IActionResult EditProject(int? id)
        {
            if (id == null)
            {
                return StatusCode(Microsoft.AspNetCore.Http.StatusCodes.Status400BadRequest);
            }
            Project project = context_.projects.Find(id);
            if (project == null)
            {
                return StatusCode(StatusCodes.Status404NotFound);
            }
            return View(project);
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public IActionResult EditProject(int? id, Project proj)
        {
            if (id == null)
            {
                return StatusCode(StatusCodes.Status400BadRequest);
            }
            var project = context_.projects.Find(id);
            if (project != null)
            {
                project.ProjectName = proj.ProjectName;
                project.Details = proj.Details;
                project.Duration = proj.Duration;
                project.Skills = proj.Skills;
                project.link = proj.link;
                project.projectImage = "/Images/" + proj.projectImage;
                try
                {
                    context_.SaveChanges();
                }
                catch (Exception)
                {
                    // do nothing for now
                }
            }
            return RedirectToAction("ProjectView");
        }


        //View Project Details

        public ActionResult projectDetails(int? id)
        {
            if (id == null)
            {
                return StatusCode(StatusCodes.Status400BadRequest);
            }
            Project project = context_.projects.Find(id);

            if (project == null)
            {
                return StatusCode(StatusCodes.Status404NotFound);
            }
            return View(project);
        }

        //Deete Project
        [Authorize(Roles = "Admin")]
        public IActionResult DeleteProject(int? id)
        {
            Project project = context_.projects.Find(id);
            context_.Entry(project).State = Microsoft.EntityFrameworkCore.EntityState.Deleted;
            context_.SaveChanges();
            return RedirectToAction("ProjectView");
        }



           //>---------------------< Honors and Awards methods >-------------------<


        public ActionResult HonorView()
        {
         
            return View(context_.honorsAndAwards.ToList<HonorsAndAwards>());
        }


        [HttpGet]
        [Authorize(Roles = "Admin")]
        public IActionResult AddHonor(int id)
        {
            var model = new HonorsAndAwards();
            return View(model);
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public IActionResult AddHonor(int id, HonorsAndAwards honor)
        {
            honor.AwardImage = "/Images/" + honor.AwardImage;
            context_.honorsAndAwards.Add(honor);
            context_.SaveChanges();
            return RedirectToAction("HonorView");
        }

        //Edit Honors

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public IActionResult EditHonor(int? id)
        {
            if (id == null)
            {
                return StatusCode(Microsoft.AspNetCore.Http.StatusCodes.Status400BadRequest);
            }
            HonorsAndAwards honor = context_.honorsAndAwards.Find(id);
            if (honor == null)
            {
                return StatusCode(StatusCodes.Status404NotFound);
            }
            return View(honor);
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public IActionResult EditHonor(int? id, HonorsAndAwards hon)
        {
            if (id == null)
            {
                return StatusCode(StatusCodes.Status400BadRequest);
            }
            var honor = context_.honorsAndAwards.Find(id);
            if (honor != null)
            {
                honor.AwardName = hon.AwardName;
                honor.AwardYear = hon.AwardYear;
                honor.AwardImage = "/Images/" + hon.AwardImage;
                try
                {
                    context_.SaveChanges();
                }
                catch (Exception)
                {
                    // do nothing for now
                }
            }
            return RedirectToAction("HonorView");
        }


        //View Honor Details

        public ActionResult HonorDetails(int? id)
        {
            if (id == null)
            {
                return StatusCode(StatusCodes.Status400BadRequest);
            }
            HonorsAndAwards honor = context_.honorsAndAwards.Find(id);

            if (honor == null)
            {
                return StatusCode(StatusCodes.Status404NotFound);
            }
            return View(honor);
        }

        //Delete Honor
        [Authorize(Roles = "Admin")]
        public IActionResult DeleteHonor(int? id)
        {
            HonorsAndAwards honor = context_.honorsAndAwards.Find(id);
            context_.Entry(honor).State = Microsoft.EntityFrameworkCore.EntityState.Deleted;
            context_.SaveChanges();
            return RedirectToAction("HonorView");
        }



        //>--------------------< Research methods >--------------------<



        public ActionResult ResearchView()
        {
            
            return View(context_.researchPublications.ToList<ResearchPublication>());
        }



        [HttpGet]
        [Authorize(Roles = "Admin")]
        public IActionResult AddResearch(int id)
        {
            var model = new ResearchPublication();
            return View(model);
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public IActionResult AddResearch(int id, ResearchPublication res)
        {
            res.researchImage = "/Images/" + res.researchImage;
            context_.researchPublications.Add(res);
            context_.SaveChanges();
            return RedirectToAction("ResearchView");
        }

        //Edit Research

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public IActionResult EditResearch(int? id)
        {
            if (id == null)
            {
                return StatusCode(Microsoft.AspNetCore.Http.StatusCodes.Status400BadRequest);
            }
            ResearchPublication res = context_.researchPublications.Find(id);
            if (res == null)
            {
                return StatusCode(StatusCodes.Status404NotFound);
            }
            return View(res);
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public IActionResult EditResearch(int? id, ResearchPublication res)
        {
            if (id == null)
            {
                return StatusCode(StatusCodes.Status400BadRequest);
            }
            var research = context_.researchPublications.Find(id);
            if (research != null)
            {
                research.researchName = res.researchName;
                research.researchYear = res.researchYear;
                research.Conference = res.Conference;
                research.link = res.link;

Anish_Nesarkar_Final_Project/Final4/Final4/Views/Achievement/AddHonor.cshtml
@model Final4.Models.HonorsAndAwards
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@{
    ViewData["Title"] = "Honors Add View";
}


<form asp-controller="Achievement" asp-action="AddHonor" method="post">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="input-group">
        <label asp-for="AwardName" class="input-group-btn"></label>
        <input asp-for="AwardName" class="form-control" />
        <span asp-validation-for="AwardName" class="text-danger"></span>
    </div>
    <div class="input-group">
        <label asp-for="AwardYear" class="input-group-btn"></label>
        <input asp-for="AwardYear" class="form-control" />
        <span asp-validation-for="AwardYear" class="text-danger"></span>
    </div>
    <div class="input-group">
        <label asp-for="AwardImage" class="input-group-btn"></label>
        <input type="file" asp-for="AwardImage" class="form-control" />
        <span asp-validation-for="AwardImage" class="text-danger"></span>
    </div>
    <div class="form-group">
        <input type="submit" value="Create" class="btn btn-primary" />
    </div>
</form>

<div style="display:block;height:30px">
</div>
<footer style="bottom:0;width:100%;position:absolute;height:2.5rem;">
    <a href="https://www.linkedin.com/in/anishnesarkar/" target="_blank"><img style="margin-top:7px;" src="~/Images/linkedlnImage.png" height="40" width="40" /></a>
    <a href="https://www.facebook.com/anish.nkr" target="_blank"><img style="margin-top:7px;margin-left:7px" src="~/Images/facebook.png" height="40" width="40" /></a>
    <a href="https://www.instagram.com/anish_nkr/?hl=en" target="_blank"><img style="margin-top:7px;margin-left:7px" src="~/Images/anish_nkr_nametag.png" height="40" width="40" /></a>
    <a style="margin-left:75%" asp-controller="Achievement" asp-action="HonorView">Back</a>
</footer>

Anish_Nesarkar_Final_Project/Final4/Final4/Views/Achievement/AddProject.cshtml
@model Final4.Models.Project
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@{
    ViewData["Title"] = "Project View";
}


<form asp-controller="Achievement" asp-action="AddProject" method="post">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="input-group">
        <label asp-for="ProjectName" class="input-group-btn"></label>
        <input style="margin-left:5%" asp-for="ProjectName" class="form-control" />
        <span asp-validation-for="ProjectName" class="text-danger"></span>
    </div>
    <div class="input-group">
        <label asp-for="Details" class="input-group-btn"></label>
        <input style="margin-left:9%" asp-for="Details" class="form-control" />
        <span asp-validation-for="Details" class="text-danger"></span>
    </div>
    <div class="input-group">
        <label asp-for="Duration" class="input-group-btn"></label>
        <input style="margin-left:8%" asp-for="Duration" class="form-control" />
        <span asp-validation-for="Duration" class="text-danger"></span>
    </div>
    <div class="input-group">
        <label asp-for="Skills" class="input-group-btn"></label>
        <input style="margin-left:10%" asp-for="Skills" class="form-control" />
        <span asp-validation-for="Skills" class="text-danger"></span>
    </div>
    <div class="input-group">
        <label asp-for="link" class="input-group-btn"></label>
        <input style="margin-left:11%" asp-for="link" class="form-control" />
        <span asp-validation-for="link" class="text-danger"></span>
    </div>
    <div class="input-group">
        <label asp-for="projectImage" class="input-group-btn"></label>
        <input style="margin-left:5%" type="file" asp-for="projectImage" class="form-control" />
        <span asp-validation-for="projectImage" class="text-danger"></span>
    </div>
    <div class="form-group">
        <input type="submit" value="Create" class="btn btn-primary" />
    </div>
</form>


<div style="display:block;height:30px">
</div>
<footer style="bottom:0;width:100%;position:absolute;height:2.5rem;">
    <a href="https://www.linkedin.com/in/anishnesarkar/" target="_blank"><img style="margin-top:7px;" src="~/Images/linkedlnImage.png" height="40" width="40" /></a>
    <a href="https://www.facebook.com/anish.nkr" target="_blank"><img style="margin-top:7px;margin-left:7px" src="~/Images/facebook.png" height="40" width="40" /></a>
    <a href="https://www.instagram.com/anish_nkr/?hl=en" target="_blank"><img style="margin-top:7px;margin-left:7px" src="~/Images/anish_nkr_nametag.png" height="40" width="40" /></a>
    <a style="margin-left:75%" asp-controller="Achievement" asp-action="ProjectView">Back</a>
</footer>

Anish_Nesarkar_Final_Project/Final4/Final4/Views/Achievement/AddResearch.cshtml
@model Final4.Models.ResearchPublication
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@{
    ViewData["Title"] = "Research Add View";
}


<form asp-controller="Achievement" asp-action="AddResearch" method="post">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="input-group">
        <label asp-for="researchName" class="input-group-btn"></label>
        <input asp-for="researchName" class="form-control" />
        <span asp-validation-for="researchName" class="text-danger"></span>
    </div>
    <div class="input-group">
        <label asp-for="Conference" class="input-group-btn"></label>
        <input asp-for="Conference" class="form-control" />
        <span asp-validation-for="Conference" class="text-danger"></span>
    </div>
    <div class="input-group">
        <label asp-for="researchYear" class="input-group-btn"></label>
        <input asp-for="researchYear" class="form-control" />
        <span asp-validation-for="researchYear" class="text-danger"></span>
    </div>
    <div class="input-group">
        <label asp-for="link" class="input-group-btn"></label>
        <input asp-for="link" class="form-control" />
        <span asp-validation-for="link" class="text-danger"></span>
    </div>
    <div class="input-group">
        <label asp-for="researchImage" class="input-group-btn"></label>
        <input type="file" asp-for="researchImage" class="form-control" />
        <span asp-validation-for="researchImage" class="text-danger"></span>
    </div>
    <div class="form-group">
        <input type="submit" value="Create" class="btn btn-primary" />
    </div>
</form>


<div style="display:block;height:30px">
</div>

<footer style="bottom:0;width:100%;position:absolute;height:2.5rem;">

    <a href="https://www.linkedin.com/in/anishnesarkar/" target="_blank"><img style="margin-top:7px;" src="~/Images/linkedlnImage.png" height="40" width="40" /></a>
    <a href="https://www.facebook.com/anish.nkr" target="_blank"><img style="margin-top:7px;margin-left:7px" src="~/Images/facebook.png" height="40" width="40" /></a>
    <a href="https://www.instagram.com/anish_nkr/?hl=en" target="_blank"><img style="margin-top:7px;margin-left:7px" src="~/Images/anish_nkr_nametag.png" height="40" width="40" /></a>
    <a style="margin-left:75%" asp-controller="Achievement" asp-action="AchievementIndex">Back</a>
    <h5 style="text-align:center"><b><a asp-action="CommentIndex">Add Comments/Notes</a></b></h5>
</footer>

Anish_Nesarkar_Final_Project/Final4/Final4/Views/Achievement/EditHonor.cshtml
@model Final4.Models.HonorsAndAwards
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@{
    ViewData["Title"] = "Edit Honors And Awards";
}


<form asp-controller="Achievement" asp-action="EditHonor" method="post">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="HonorsAndAwardsId" />
    <div class="input-group">
        <label asp-for="AwardName" class="input-group-btn"></label>
        <input style="margin-left:10px" asp-for="AwardName" class="form-control" />
        <span asp-validation-for="AwardName" class="text-danger"></span>

    </div>
    <div class="input-group">
        <label asp-for="AwardYear" class="input-group-btn"></label>
        <input style="margin-left:53px" asp-for="AwardYear" class="form-control" />
        <span asp-validation-for="AwardYear" class="text-danger"></span>
    </div>
    <div class="input-group">
        <label asp-for="AwardImage" class="input-group-btn"></label>
        <input style="margin-left:9px" type="file" asp-for="AwardImage" class="form-control" />
        <span asp-validation-for="AwardImage" class="text-danger"></span>
    </div>
    <div class="form-group">
        <input type="submit" value="Save" class="btn btn-primary" />
    </div>
</form>

<div style="display:block;height:30px">
</div>
<footer style="bottom:0;width:100%;position:absolute;height:2.5rem;">
    <a href="https://www.linkedin.com/in/anishnesarkar/" target="_blank"><img style="margin-top:7px;" src="~/Images/linkedlnImage.png" height="40" width="40" /></a>
    <a href="https://www.facebook.com/anish.nkr" target="_blank"><img style="margin-top:7px;margin-left:7px" src="~/Images/facebook.png" height="40" width="40" /></a>
    <a href="https://www.instagram.com/anish_nkr/?hl=en" target="_blank"><img style="margin-top:7px;margin-left:7px" src="~/Images/anish_nkr_nametag.png" height="40" width="40" /></a>
    <a style="margin-left:75%" asp-controller="Achievement" asp-action="HonorView">Back</a>
</footer>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Anish_Nesarkar_Final_Project/Final4/Final4/Views/Achievement/EditProject.cshtml
@model Final4.Models.Project
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@{
    ViewData["Title"] = "Edit Project";
}


<form asp-controller="Achievement" asp-action="EditProject" method="post">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="ProjectId" />
    <div class="input-group">

        <label asp-for="ProjectName" class="input-group-btn"></label>

        <input style="margin-left:10px" asp-for="ProjectName" class="form-control" />

        <span asp-validation-for="ProjectName" class="text-danger"></span>

    </div>
    <div class="input-group">
        <label asp-for="Details" class="input-group-btn"></label>
        <input style="margin-left:53px" asp-for="Details" class="form-control" />
        <span asp-validation-for="Details" class="text-danger"></span>
    </div>
    <div class="input-group">
        <label asp-for="Duration" class="input-group-btn"></label>
        <input style="margin-left:40px" asp-for="Duration" class="form-control" />
        <span asp-validation-for="Duration" class="text-danger"></span>
    </div>
    <div class="input-group">
        <label asp-for="Skills" class="input-group-btn"></label>
        <input style="margin-left:67px" asp-for="Skills" class="form-control" />
        <span asp-validation-for="Skills" class="text-danger"></span>
    </div>
    <div class="input-group">
        <label asp-for="link" class="input-group-btn"></label>
        <input style="margin-left:77px" asp-for="link" class="form-control" />
        <span asp-validation-for="link" class="text-danger"></span>
    </div>
    <div class="input-group">
        <label asp-for="projectImage" class="input-group-btn"></label>
        <input style="margin-left:9px" type="file" asp-for="projectImage" class="form-control" />
        <span asp-validation-for="projectImage" class="text-danger"></span>
    </div>
    <div class="form-group">
        <input type="submit" value="Save" class="btn btn-primary" />
    </div>
</form>

<div style="display:block;height:30px">
</div>
<footer style="bottom:0;width:100%;position:absolute;height:2.5rem;">
    <a href="https://www.linkedin.com/in/anishnesarkar/" target="_blank"><img style="margin-top:7px;" src="~/Images/linkedlnImage.png" height="40" width="40" /></a>
    <a href="https://www.facebook.com/anish.nkr" target="_blank"><img style="margin-top:7px;margin-left:7px" src="~/Images/facebook.png" height="40" width="40" /></a>
    <a href="https://www.instagram.com/anish_nkr/?hl=en" target="_blank"><img style="margin-top:7px;margin-left:7px" src="~/Images/anish_nkr_nametag.png" height="40" width="40" /></a>
    <a style="margin-left:75%" asp-controller="Achievement" asp-action="ProjectView">Back</a>
</footer>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Anish_Nesarkar_Final_Project/Final4/Final4/Views/Achievement/EditResearch.cshtml
@model Final4.Models.ResearchPublication
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@{
    ViewData["Title"] = "Edit Research";
}


<form asp-controller="Achievement" asp-action="EditResearch" method="post">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for=" ResearchPublicationId" />
    <div class="input-group">

        <label asp-for="researchName" class="input-group-btn"></label>

        <input style="margin-left:10px" asp-for="researchName" class="form-control" />

        <span asp-validation-for="researchName" class="text-danger"></span>

    </div>
    <div class="input-group">
        <label asp-for="Conference" class="input-group-btn"></label>
        <input style="margin-left:53px" asp-for="Conference" class="form-control" />
        <span asp-validation-for="Conference" class="text-danger"></span>
    </div>
    <div class="input-group">
        <label asp-for="researchYear" class="input-group-btn"></label>
        <input style="margin-left:40px" asp-for="researchYear" class="form-control" />
        <span asp-validation-for="researchYear" class="text-danger"></span>
    </div>
    <div class="input-group">
        <label asp-for="link" class="input-group-btn"></label>
        <input style="margin-left:77px" asp-for="link" class="form-control" />
        <span asp-validation-for="link" class="text-danger"></span>
    </div>
    <div class="input-group">
        <label asp-for="researchImage" class="input-group-btn"></label>
        <input style="margin-left:9px" type="file" asp-for="researchImage" class="form-control" />
        <span asp-validation-for="researchImage" class="text-danger"></span>
    </div>
    <div class="form-group">
        <input type="submit" value="Save" class="btn btn-primary" />
    </div>
</form>

<div style="display:block;height:30px">
</div>

<footer style="bottom:0;width:100%;position:absolute;height:2.5rem;">

    <a href="https://www.linkedin.com/in/anishnesarkar/" target="_blank"><img style="margin-top:7px;" src="~/Images/linkedlnImage.png" height="40" width="40" /></a>
    <a href="https://www.facebook.com/anish.nkr" target="_blank"><img style="margin-top:7px;margin-left:7px" src="~/Images/facebook.png" height="40" width="40" /></a>
    <a href="https://www.instagram.com/anish_nkr/?hl=en" target="_blank"><img style="margin-top:7px;margin-left:7px" src="~/Images/anish_nkr_nametag.png" height="40" width="40" /></a>
    <a style="margin-left:75%" asp-controller="Achievement" asp-action="AchievementIndex">Back</a>
    <h5 style="text-align:center"><b><a asp-action="CommentIndex">Add Comments/Notes</a></b></h5>
</footer>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Anish_Nesarkar_Final_Project/Final4/Final4/Views/Achievement/HonorDetails.cshtml
@model Final4.Models.HonorsAndAwards

@{
    ViewData["Title"] = "projectDetails";
}


<div style="display:flex;margin-top:50px;justify-content:center">
    <img src="@Html.DisplayFor(model => model.AwardImage)" width="300" height="300" />
</div>

<div style="display:flex;justify-content:center;margin-top:10px;font-size:20px;color:aquamarine">
    <b><u> @Html.DisplayFor(model => model.AwardName) </u></b>
</div>
<div style="display:flex;justify-content:center">
    @Html.DisplayFor(model => model.AwardYear)
</div>
<div style="display:block;height:30px">
</div>
<footer style="bottom:0;width:100%;position:absolute;height:2.5rem;">
    <a href="https://www.linkedin.com/in/anishnesarkar/" target="_blank"><img style="margin-top:7px;" src="~/Images/linkedlnImage.png" height="40" width="40" /></a>
    <a href="https://www.facebook.com/anish.nkr" target="_blank"><img style="margin-top:7px;margin-left:7px" src="~/Images/facebook.png" height="40" width="40" /></a>
    <a href="https://www.instagram.com/anish_nkr/?hl=en" target="_blank"><img style="margin-top:7px;margin-left:7px" src="~/Images/anish_nkr_nametag.png" height="40" width="40" /></a>
    <a style="margin-left:75%" asp-controller="Achievement" asp-action="HonorView">Back</a>
</footer>

Anish_Nesarkar_Final_Project/Final4/Final4/Views/Achievement/HonorView.cshtml
@model IEnumerable<Final4.Models.HonorsAndAwards>

@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@{
    ViewData["Title"] = "Honor View";

}

<div>
    <img src="~/Images/AwardsImage.png" height="400" width="1100" />
</div>

@if (User.IsInRole("Admin"))
{
    <div style="display:flex;justify-content:flex-end">
        <a asp-action="AddHonor">Add New Honor</a>
    </div>
}
<div style="display:flex;width:1200px; justify-content:space-around">
    @foreach (var item in Model)
    {

        <div style="display:block;width:250px;height:100px;background-color:aquamarine;padding:70px 0;text-align:center">
            <a asp-action="HonorDetails" asp-route-id="@item.HonorsAndAwardsId">
                @Html.DisplayFor(modelItem => item.AwardName)
            </a>
            @if (User.IsInRole("Admin"))
            {
                <p></p>
                <span><                  </span>
                <a asp-action="EditHonor" asp-route-id="@item.HonorsAndAwardsId">Edit</a> <span> | </span>
                <a asp-action="DeleteHonor" asp-route-id="@item.HonorsAndAwardsId">Delete</a> <span> > </span>

            }
        </div>


    }

</div>
<div style="display:block;height:30px">
</div>
<footer style="bottom:0;width:100%;position:absolute;height:2.5rem;">

    <a href="https://www.linkedin.com/in/anishnesarkar/" target="_blank"><img style="margin-top:7px;" src="~/Images/linkedlnImage.png" height="40" width="40" /></a>
    <a href="https://www.facebook.com/anish.nkr" target="_blank"><img style="margin-top:7px;margin-left:7px" src="~/Images/facebook.png" height="40" width="40" /></a>
    <a href="https://www.instagram.com/anish_nkr/?hl=en" target="_blank"><img style="margin-top:7px;margin-left:7px" src="~/Images/anish_nkr_nametag.png" height="40" width="40" /></a>
    <a style="margin-left:75%" asp-controller="Achievement" asp-action="AchievementIndex">Back</a>
    <h5 style="text-align:center"><b><a asp-action="CommentIndex">Add Comments/Notes</a></b></h5>
</footer>